-- 4일차 집합연산자
-- 1.1 합집합
-- 1.1.1 UNION(중복제거)
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 1.1.2 UNION ALL(중복허용)
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION ALL
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;

-- 1.1.3 UNION 사용조건
-- 1. 컬럼의 갯수가 같아야 함
-- 2. 컬럼의 데이터타입이 각각 같아야 함
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
UNION
-- ORA-01790: expression must have same datatype as corresponding expression
SELECT EMP_NAME, EMP_ID FROM EMPLOYEE --EMP_ID를 TO_NUMBER(EMP_ID)로 해주면 해결
WHERE SALARY >= 2400000;


-- 1.2 교집합
-- 1.2.1 INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
INTERSECT
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;


-- 1.3 차집합
-- 1.3.1 MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE DEPT_CODE = 'D5'
MINUS
SELECT EMP_NAME, SALARY FROM EMPLOYEE
WHERE SALARY >= 2400000;







