-- 3일차
-- DDL, Data Definition Language 데이터 정의어
-- CREATE, ALTER, DROP           DDL의 종류
-- CREATE USER, CREATE TABLE, ...예시
-- DROP TABLE, ...
-- ALTER로 할 수 있었던 것
-- 컬럼추가, 컬럼삭제, 컬럼수정(데이터타입, 이름), 테이블명 수정 2가지

-- 제약조건 추가, 삭제, 수정
-- 제약조건을 추가하면 이름이 생김, 이름을 알아야 삭제 가능

-- 제약조건 조회 쿼리
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

-- 제약조건 삭제 쿼리
ALTER TABLE USER_TBL
DROP CONSTRAINT SYS_C007138;

-- 제약조권 추가 쿼리
-- CONTRAINT FK_GRADE_CODE -> 제약조건에 이름 붙이기
-- NOT NULL 추가는 좀 다름..
-- 제약조건명을 따로 붙이지 않음.
ALTER TABLE USER_TBL
MODIFY USER_ID NOT NULL;    --MODIFY 로 추가해야한다
--USER_ID   VARCHAR(20) -> USER_ID NOT NULL VARCHAR2(20)

ALTER TABLE USER_TBL
MODIFY USER_DATE DEFAULT SYSDATE;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

DESC USER_TBL;




ALTER TABLE USER_TBL
ADD CONSTRAINT FK_GRADE_CODE
-- 제약조건 외래키 추가 부분
FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE);


SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';
-- 1. 실행하면 ROW 1개 존재
-- 2. CONSTRAINT_NAME이 FK_GRADE_CODE인 것 확인



-- ex) USER_GRADE가 가지고있는 제약조건 조회하여 삭제 후 같은 이름으로 재생성
-- 제약조건 수정은 삭제하고 다시 추가해야 한다, 단 이름은 바꿀 수 있음

ALTER TABLE USER_GRADE
RENAME CONSTRAINT PK_GRADE_CODE TO PRIMARYKEY_GR_CODE;

-- 제약조건 조회
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL';

-- 제약조건 삭제
ALTER TABLE USER_TBL
DROP CONSTRAINT FK_GRADE_CODE;

-- 제약조건 재생성
ALTER TABLE USER_TBL
ADD CONSTRAINT PK_GRADE_CODE PRIMARY KEY(GRADE_CODE);

DESC USER_TBL;










-- EX01) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 추가해주세요
DESC USER_FOREIGN_KEY;
ALTER TABLE USER_FOREIGN_KEY
ADD USER_DATE DATE;
-- EX02) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼을 삭제해주세요
ALTER TABLE USER_FOREIGN_KEY
DROP COLUMN USER_DATE;
-- EX03) USER_FOREIGN_KEY 테이블에 USER_DATE 컬럼의 자료형을 VARCHAR2(10)으로 바꿔주세요
ALTER TABLE USER_FOREIGN_KEY
MODIFY USER_DATE VARCHAR(10);
-- EX04) USER_FOREIGN_KEY 테이블에 USER_DATE DATE 컬럼의 이름을 REG_DATE로 변경해주세요
ALTER TABLE USER_FOREIGN_KEY
RENAME COLUMN USER_DATE TO REG_DATE;

ALTER TABLE USER_FOREIGN_KEY
RENAME COLUMN REG_DATE TO USER_DATE;

-- USER_DATE의 VARCHAR2(10)을 DATE로 바꿔주세요
ALTER TABLE USER_FOREIGN_KEY
MODIFY USER_DATE DATE;
DESC USER_FOREIGN_KEY;

-- EX05) USER_FOREIGN_KEY 테이블의 이름을 USER_TBL로 바꿔주세요 (2가지)
ALTER TABLE USER_FOREIGN_KEY
RENAME TO USER_TBL;

ALTER TABLE USER_TBL 
RENAME TO USER_FOREIGN_KEY;






-- 제약조건 활성화/비활성화
-- 비활성화
ALTER TABLE USER_TBL
DISABLE CONSTRAINT PK_GRADE_CODE;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL'; --결과값 중 STATUS 항목 확인

-- 활성화
ALTER TABLE USER_TBL
ENABLE CONSTRAINT PK_GRADE_CODE;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'USER_TBL'; --결과값 중 STATUS 항목 확인