SHOW USER;

GRANT CONNECT TO KHUSER01;

GRANT RESOURCE TO KHUSER01;

CREATE USER KHUSER03 IDENTIFIED BY KHUSER03;

DROP USER KHUSER03;

SELECT * FROM dba_data_files;

SELECT * FROM user_users;


SELECT USERNAME, ACCOUNT_STATUS, LOCK_DATE, EXPIRY_DATE FROM DBA_USERS WHERE ACCOUNT_STATUS LIKE '%EXPIRED%';

SELECT RESOURCE_NAME, LIMIT FROM DBA_PROFILES WHERE PROFILE='DEFAULT';